// Generated by model-gen tool. Do not edit but rather edit the template in utils/class-template.go.tmpl 
package model

import (
	"database/sql"
	"errors"
	"fmt"
	"time"
	
	_ "github.com/mutecomm/go-sqlcipher/v4"
)

type Property_manager struct {
	Address string `db:"address"`
	Contact_number string `db:"contact_number"`
	Email string `db:"email"`
	First_name string `db:"first_name"`
	Id int64 `db:"id"`
	Join_date int64 `db:"join_date"`
	Last_name string `db:"last_name"`
	Note string `db:"note"`
	
	Where string 
}

func NewProperty_manager(email string ) Property_manager {

	o := Property_manager{}
	if err := DB.Get(&o, "SELECT * FROM property_manager WHERE  email = ?",email ); errors.Is(err, sql.ErrNoRows) {		
		o.Email = email
		if o.Join_date == 0 {
			o.Join_date = time.Now().Unix()
		}
		o.Save()
	}
	// get one and test if exists return as it is
	return o	
}

func GetProperty_manager(email string) *Property_manager {
	o := Property_manager{
		Email: email , 
		Where: "email=:email "}
	if r := o.Search(); r != nil {
		return &r[0]
	} else {
		return nil
	}
}

func GetProperty_managerByID(id int64) *Property_manager {
	o := Property_manager{
		Id: id,
		Where: "id=:id"}
	if r := o.Search(); r != nil {
		return &r[0]
	} else {
		return nil
	}
}

// Search func
func (o *Property_manager) Search() []Property_manager {
	output := []Property_manager{}
	if rows, err := DB.NamedQuery(fmt.Sprintf(`SELECT * FROM property_manager WHERE %s`, o.Where), o); err == nil {
		for rows.Next() {
			_t := Property_manager{}
			if er := rows.StructScan(&_t); er == nil {
				output = append(output, _t)
			} else {
				fmt.Printf("[ERROR] Scan %s\n", er.Error())
				continue
			}
		}
	} else {
		fmt.Printf("[ERROR] NamedQuery %s\n", err.Error())
	}
	return output
}

// Save existing object which is saved it into db 
func (o *Property_manager) Save() {
	if res, err := DB.NamedExec(`INSERT INTO property_manager(join_date,first_name,last_name,address,contact_number,email,note ) VALUES(:join_date,:first_name,:last_name,:address,:contact_number,:email,:note ) ON CONFLICT(email) DO UPDATE SET join_date=excluded.join_date,first_name=excluded.first_name,last_name=excluded.last_name,address=excluded.address,contact_number=excluded.contact_number,email=excluded.email,note=excluded.note`, o); err != nil {
		fmt.Printf("[ERROR] %s\n", err.Error())
	} else {
		o.Id, _ = res.LastInsertId()
	}
}

// Delete one object
func (o *Property_manager) Delete() {
	if _, err := DB.NamedExec(`DELETE FROM property_manager WHERE email=:email`, o); err != nil {
		fmt.Printf("[ERROR] %s\n", err.Error())
	} else {
		o = nil
	}
}

func DeleteProperty_managerByID(id int64) {
	if _, err := DB.NamedExec(`DELETE FROM property_manager WHERE id=?`, id); err != nil {
		fmt.Printf("[ERROR] %s\n", err.Error())
	}
}