// Generated by model-gen tool. Do not edit but rather edit the template in utils/class-template.go.tmpl
package model

import (
	"database/sql"
	"errors"
	"fmt"
	_ "github.com/mutecomm/go-sqlcipher/v4"
	ag "github.com/sunshine69/automation-go/lib"
	"os"
	"strings"
)

type Property struct {
	Address string `db:"address"`
	Id      int64  `db:"id"`
	Name    string `db:"name"`
	Note    string `db:"note"`

	Where string
}

func NewProperty(name string) Property {

	o := Property{}
	if err := DB.Get(&o, "SELECT * FROM property WHERE  name = ?", name); errors.Is(err, sql.ErrNoRows) {
		o.Name = name
		o.Save()
	}
	// get one and test if exists return as it is
	return o
}

func GetPropertyByCompositeKey(data map[string]interface{}) *Property {
	if rows, err := DB.NamedQuery(`SELECT * FROM property WHERE name=:name `, data); err == nil {
		defer rows.Close()
		for rows.Next() {
			tn := Property{}
			if err = rows.StructScan(&tn); err == nil {
				return &tn
			} else {
				fmt.Fprintf(os.Stderr, "[ERROR] GetPropertyByCompositeKey %s\n", err.Error())
				return nil
			}
		}
	} else {
		fmt.Fprintf(os.Stderr, "[ERROR] GetPropertyByCompositeKey %s\n", err.Error())
	}
	return nil
}

func GetProperty(name string) *Property {
	o := Property{
		Name:  name,
		Where: "name=:name "}
	if r := o.Search(); len(r) > 0 {
		return &r[0]
	} else {
		return nil
	}
}

func GetPropertyByID(id int64) *Property {
	o := Property{
		Id:    id,
		Where: "id=:id"}
	if r := o.Search(); len(r) > 0 {
		return &r[0]
	} else {
		return nil
	}
}

// Search func
func (o *Property) Search() []Property {
	output := []Property{}
	if rows, err := DB.NamedQuery(fmt.Sprintf(`SELECT * FROM property WHERE %s`, o.Where), o); err == nil {
		defer rows.Close()
		for rows.Next() {
			_t := Property{}
			if er := rows.StructScan(&_t); er == nil {
				output = append(output, _t)
			} else {
				fmt.Printf("[ERROR] Scan %s\n", er.Error())
				continue
			}
		}
	} else {
		fmt.Printf("[ERROR] NamedQuery %s\n", err.Error())
	}
	return output
}

// Save new object which is saved it into db
func (o *Property) Update(data map[string]interface{}) error {
	fields := ag.MapKeysToSlice(data)
	fieldsWithoutKey := ag.SliceMap(fields, func(s string) *string {
		if s != "id" && s != "email" {
			return &s
		}
		return nil
	})
	updateFields := ag.SliceMap(fieldsWithoutKey, func(s string) *string { s = s + " = :" + s; return &s })
	updateFieldsStr := strings.Join(updateFields, ",")

	if _, err := DB.NamedExec(`UPDATE property SET `+updateFieldsStr, data); err != nil {
		return err
	}
	return nil
}

// Save existing object which is saved it into db
func (o *Property) Save() error {
	if res, err := DB.NamedExec(`INSERT INTO property(address,name,note ) VALUES(:address,:name,:note)`, o); err != nil {
		return err
	} else {
		o.Id, _ = res.LastInsertId()
	}
	return nil
}

// Delete one object
func (o *Property) Delete() error {
	if res, err := DB.NamedExec(`DELETE FROM property WHERE name=:name `, o); err != nil {
		return err
	} else {
		r, err := res.RowsAffected()
		if err != nil {
			return err
		}
		if r == 0 {
			return fmt.Errorf("ERROR property not found")
		}
	}
	return nil
}

func DeletePropertyByID(id int64) error {
	// sqlx bug? If directly use Exec and sql is a pure string it never delete it but still return ok
	// looks like we always need to bind the named query with sqlx - can not parse pure string in
	if res, err := DB.NamedExec(`DELETE FROM property WHERE id = :id`, map[string]interface{}{"id": id}); err != nil {
		return err
	} else {
		r, err := res.RowsAffected()
		if err != nil {
			return err
		}
		if r == 0 {
			return fmt.Errorf("ERROR property not found")
		}
	}
	return nil
}
