// Generated by api-gen tool. Do not edit here but edit in api/api-template.go.tmpl 
package api

import (
	"fmt"
	"net/http"

	u "github.com/sunshine69/golang-tools/utils"

	"github.com/sunshine69/rental-management/model"
)

func CreateAccount(w http.ResponseWriter, r *http.Request) {
	account := ParseJSON[model.Account](r)
	account.Save()
}

func UpdateAccount(w http.ResponseWriter, r *http.Request) {
	o := ParseJSON[model.Account](r)
	if id := ParseID(r); id != 0 {
		o.Id = id
		o.Save()
		fmt.Fprint(w, `{"status": "OK", "msg": "Account updated"}`)
		return
	} else {    
		if o.Contract_id == 0  {
			fmt.Fprint(w, `{"status": "ERROR", "msg": "Account no key value not provided"}`)
			return
		} else {
			o.Save()
			fmt.Fprint(w, `{"status": "OK", "msg": "Account updated"}`)
			return
		}
	}
}

func DeleteAccount(w http.ResponseWriter, r *http.Request) {
	if id := ParseID(r); id != 0 {
		model.DeleteAccountByID(id)
		fmt.Fprint(w, `{"status": "OK", "msg": "Account deleted"}`)
		return
	} else {
		account := ParseJSON[model.Account](r)
		if account.Id != 0 {
			account.Delete()
			fmt.Fprint(w, `{"status": "OK", "msg": "Account deleted"}`)
		}
	}
}

func GetAccount(w http.ResponseWriter, r *http.Request) {
	if id := ParseID(r); id == 0 {
		if where := r.PathValue("where"); where != "" {
			o := model.Account{Where: where}
			os := o.Search()
			fmt.Fprint(w, u.JsonDump(os, ""))
			return
		} else {
			os := []model.Account{}
			model.DB.Select(&os, `SELECT * FROM account ORDER BY id LIMIT 200`)
			fmt.Fprint(w, u.JsonDump(os, ""))
			return
		}
	} else {
		o := model.GetAccountByID(id)
		fmt.Fprint(w, u.JsonDump(*o, ""))
		return
	}
}

func AccountRouteRegister(mux *http.ServeMux, PathBase string) {
	mux.HandleFunc("POST "+PathBase+"/account", CreateAccount)
	mux.HandleFunc("PUT "+PathBase+"/account/{id}{$}", UpdateAccount)
	mux.HandleFunc("PUT "+PathBase+"/account", UpdateAccount)
	mux.HandleFunc("DELETE "+PathBase+"/account/{id}{$}", DeleteAccount)
	mux.HandleFunc("DELETE "+PathBase+"/account", DeleteAccount)
	mux.HandleFunc("GET "+PathBase+"/account", GetAccount)
	mux.HandleFunc("GET "+PathBase+"/account/{id}{$}", GetAccount)
	mux.HandleFunc("GET "+PathBase+"/account/{where}{$}", GetAccount)
}
