// Generated by api-gen tool. Do not edit here but edit in api/api-template.go.tmpl 
package api

import (
	"fmt"
	"net/http"

	u "github.com/sunshine69/golang-tools/utils"

	"github.com/sunshine69/rental-management/model"
)

func CreateContract(w http.ResponseWriter, r *http.Request) {
	contract := ParseJSON[model.Contract](r)
	contract.Save()
}

func UpdateContract(w http.ResponseWriter, r *http.Request) {
	o := ParseJSON[model.Contract](r)
	if id := ParseID(r); id != 0 {
		o.Id = id
		o.Save()
		fmt.Fprint(w, `{"status": "OK", "msg": "Contract updated"}`)
		return
	} else {    
		if o.Property_id == 0  || o.Tenant_id == 0  || o.Signed_date == 0  {
			fmt.Fprint(w, `{"status": "ERROR", "msg": "Contract no key value not provided"}`)
			return
		} else {
			o.Save()
			fmt.Fprint(w, `{"status": "OK", "msg": "Contract updated"}`)
			return
		}
	}
}

func DeleteContract(w http.ResponseWriter, r *http.Request) {
	if id := ParseID(r); id != 0 {
		model.DeleteContractByID(id)
		fmt.Fprint(w, `{"status": "OK", "msg": "Contract deleted"}`)
		return
	} else {
		contract := ParseJSON[model.Contract](r)
		if contract.Id != 0 {
			contract.Delete()
			fmt.Fprint(w, `{"status": "OK", "msg": "Contract deleted"}`)
		}
	}
}

func GetContract(w http.ResponseWriter, r *http.Request) {
	if id := ParseID(r); id == 0 {
		if where := r.PathValue("where"); where != "" {
			o := model.Contract{Where: where}
			os := o.Search()
			fmt.Fprint(w, u.JsonDump(os, ""))
			return
		} else {
			os := []model.Contract{}
			model.DB.Select(&os, `SELECT * FROM contract ORDER BY id LIMIT 200`)
			fmt.Fprint(w, u.JsonDump(os, ""))
			return
		}
	} else {
		o := model.GetContractByID(id)
		fmt.Fprint(w, u.JsonDump(*o, ""))
		return
	}
}

func ContractRouteRegister(mux *http.ServeMux, PathBase string) {
	mux.HandleFunc("POST "+PathBase+"/contract", CreateContract)
	mux.HandleFunc("PUT "+PathBase+"/contract/{id}{$}", UpdateContract)
	mux.HandleFunc("PUT "+PathBase+"/contract", UpdateContract)
	mux.HandleFunc("DELETE "+PathBase+"/contract/{id}{$}", DeleteContract)
	mux.HandleFunc("DELETE "+PathBase+"/contract", DeleteContract)
	mux.HandleFunc("GET "+PathBase+"/contract", GetContract)
	mux.HandleFunc("GET "+PathBase+"/contract/{id}{$}", GetContract)
	mux.HandleFunc("GET "+PathBase+"/contract/{where}{$}", GetContract)
}
