// Generated by api-gen tool. Do not edit here but edit in api/api-template.go.tmpl 
package api

import (
	"fmt"
	"net/http"

	u "github.com/sunshine69/golang-tools/utils"

	"github.com/sunshine69/rental-management/model"
)

func CreateProperty(w http.ResponseWriter, r *http.Request) {
	property := ParseJSON[model.Property](r)
	property.Save()
}

func UpdateProperty(w http.ResponseWriter, r *http.Request) {
	o := ParseJSON[model.Property](r)
	if id := ParseID(r); id != 0 {
		o.Id = id
		o.Save()
		fmt.Fprint(w, `{"status": "OK", "msg": "Property updated"}`)
		return
	} else {    
		if o.Name == ""  {
			fmt.Fprint(w, `{"status": "ERROR", "msg": "Property no key value not provided"}`)
			return
		} else {
			o.Save()
			fmt.Fprint(w, `{"status": "OK", "msg": "Property updated"}`)
			return
		}
	}
}

func DeleteProperty(w http.ResponseWriter, r *http.Request) {
	if id := ParseID(r); id != 0 {
		model.DeletePropertyByID(id)
		fmt.Fprint(w, `{"status": "OK", "msg": "Property deleted"}`)
		return
	} else {
		property := ParseJSON[model.Property](r)
		if property.Id != 0 {
			property.Delete()
			fmt.Fprint(w, `{"status": "OK", "msg": "Property deleted"}`)
		}
	}
}

func GetProperty(w http.ResponseWriter, r *http.Request) {
	if id := ParseID(r); id == 0 {
		if where := r.PathValue("where"); where != "" {
			o := model.Property{Where: where}
			os := o.Search()
			fmt.Fprint(w, u.JsonDump(os, ""))
			return
		} else {
			os := []model.Property{}
			model.DB.Select(&os, `SELECT * FROM property ORDER BY id LIMIT 200`)
			fmt.Fprint(w, u.JsonDump(os, ""))
			return
		}
	} else {
		o := model.GetPropertyByID(id)
		fmt.Fprint(w, u.JsonDump(*o, ""))
		return
	}
}

func PropertyRouteRegister(mux *http.ServeMux, PathBase string) {
	mux.HandleFunc("POST "+PathBase+"/property", CreateProperty)
	mux.HandleFunc("PUT "+PathBase+"/property/{id}{$}", UpdateProperty)
	mux.HandleFunc("PUT "+PathBase+"/property", UpdateProperty)
	mux.HandleFunc("DELETE "+PathBase+"/property/{id}{$}", DeleteProperty)
	mux.HandleFunc("DELETE "+PathBase+"/property", DeleteProperty)
	mux.HandleFunc("GET "+PathBase+"/property", GetProperty)
	mux.HandleFunc("GET "+PathBase+"/property/{id}{$}", GetProperty)
	mux.HandleFunc("GET "+PathBase+"/property/{where}{$}", GetProperty)
}
